# Generated by Django 4.2.7 on 2024-01-29 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_category_articale_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='title',
            field=models.CharField(default='iran', max_length=50),
            preserve_default=False,
        ),
    ]
