# Generated by Django 4.2.7 on 2024-02-03 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_articale_descryption_alter_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='articale',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
