# Generated by Django 4.2.7 on 2024-02-11 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_articale_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articale',
            options={'ordering': ['date'], 'verbose_name': 'POST'},
        ),
        migrations.AddField(
            model_name='articale',
            name='genrate_descryption',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='articale',
            name='descryption',
            field=models.TextField(blank=True, null=True),
        ),
    ]
